### ISSUE TITLE
Todo: Add Auto version increment

### ISSUE THREAD

**Issue by thisRedH** [thisRedH/PurpurMC-Docker-#8]
Add a Workflow, that automatically bumps the default Version.

- [ ] Version checking with fetching form [Purpur Api](https://api.purpurmc.org/v2/purpur/) see [Docs](https://purpurmc.org/docs/#downloads)
- [ ] Auto update README on GitHub and Docker-Hub
- [ ] Update in dockerfile
- [ ] Run Docker push with version x.x+1.x (e.g. 2.1.0 from 2.0.0) when Minecraft get a "minor" update, and x.x.x+1 (e.g. 2.0.1 from 2.0.0) if it gets a patch
